name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 处理Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: 安装 MCDReforged
        run: pip install mcdreforged

      - name: 打包插件
        run: mcdreforged pack -n KMST_${{ github.event.head_commit.id }}.mcdr

      - name: 提交文件
        uses: actions/upload-artifact@v4
        with:
          name: "打包的插件"
          path: |
            KMST_${{ github.event.head_commit.id }}.mcdr
